"""
Demo: Programmatic Tool Generation
Usage:
    python demo.py --mock
    python demo.py --real
"""

import argparse
import json
import os
import sys

from experiment import (
    tool, tools_from_openapi, EXAMPLE_TOOLS, SAMPLE_OPENAPI_SPEC,
    ToolDefinition,
)


# ---------------------------------------------------------------------------
# Mock: show generated schemas
# ---------------------------------------------------------------------------

def mock_demo() -> None:
    print("\n=== Programmatic Tool Generation Demo [MOCK] ===\n")

    # 1. Show schemas generated by @tool decorator
    print("── @tool decorator — generated schemas ──────────────────────────\n")
    for td in EXAMPLE_TOOLS:
        print(f"  @tool: {td.name}")
        schema = json.dumps(td.api_schema, indent=4)
        for line in schema.splitlines():
            print(f"    {line}")
        print()

    # 2. Show schemas generated from OpenAPI spec
    print("── tools_from_openapi — generated schemas ───────────────────────\n")
    openapi_tools = tools_from_openapi(SAMPLE_OPENAPI_SPEC)
    for schema in openapi_tools:
        print(f"  operation: {schema['name']}")
        print(f"    description: {schema['description']}")
        props = schema['input_schema'].get('properties', {})
        if props:
            for pname, pschema in props.items():
                print(f"    param: {pname} ({pschema.get('type', '?')}) — {pschema.get('description', '')}")
        print()

    # 3. Show generating a new tool inline
    print("── Inline @tool example ─────────────────────────────────────────\n")

    @tool
    def send_notification(
        recipient: str,
        message: str,
        priority: str = "normal",
    ) -> str:
        """
        Send a notification to a user.

        Args:
            recipient: User ID or email of the notification recipient.
            message: The notification message to send.
            priority: Message priority: 'low', 'normal', or 'high'.
        """
        return f"Notification sent to {recipient}: {message}"

    print("  @tool send_notification generated schema:")
    schema = json.dumps(send_notification.api_schema, indent=4)
    for line in schema.splitlines():
        print(f"    {line}")


# ---------------------------------------------------------------------------
# Real: use generated tools in an actual API call
# ---------------------------------------------------------------------------

def real_session(user_message: str) -> None:
    import anthropic

    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

    # Use the schemas generated by @tool decorator
    api_schemas = [td.api_schema for td in EXAMPLE_TOOLS]
    tool_map = {td.name: td for td in EXAMPLE_TOOLS}

    print(f"\nUser: {user_message}")
    print(f"  [using {len(api_schemas)} programmatically generated tools]")

    messages = [{"role": "user", "content": user_message}]

    while True:
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=1024,
            tools=api_schemas,
            messages=messages,
        )

        assistant_content = response.content
        messages.append({"role": "assistant", "content": assistant_content})

        if response.stop_reason == "end_turn":
            for block in assistant_content:
                if hasattr(block, "text"):
                    print(f"Assistant: {block.text}")
            break

        if response.stop_reason == "tool_use":
            tool_results = []
            for block in assistant_content:
                if block.type == "tool_use":
                    print(f"  [tool_use] {block.name}({block.input})")
                    td = tool_map.get(block.name)
                    result = td(**block.input) if td else f"Unknown tool: {block.name}"
                    print(f"  [tool_result] {result}")
                    tool_results.append({
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": str(result),
                    })
            messages.append({"role": "user", "content": tool_results})


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run_demo(use_mock: bool) -> None:
    if use_mock:
        mock_demo()
        return

    print(f"\n=== Programmatic Tool Generation Demo [REAL] ===")
    print("Tools are generated from Python function signatures and docstrings.")
    print("\nExample queries:")
    for q in ["What's the weather in Tokyo in Fahrenheit?", "What's 2^16?", "Find user U1042."]:
        print(f"  • {q}")
    print("\nType a question or 'quit' to exit.\n")

    while True:
        try:
            user_input = input("You: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nGoodbye!")
            break
        if not user_input or user_input.lower() == "quit":
            break
        real_session(user_input)
        print()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--mock", action="store_true")
    group.add_argument("--real", action="store_true")
    args = parser.parse_args()

    if args.real and not os.environ.get("ANTHROPIC_API_KEY"):
        print("Error: ANTHROPIC_API_KEY not set.")
        sys.exit(1)

    run_demo(use_mock=args.mock)
